# Generated by Django 4.2.1 on 2023-06-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('body', models.TextField(max_length=100, verbose_name='Описание задачи')),
                ('open_date', models.DateTimeField(verbose_name='Задача открыта')),
                ('close_date', models.DateTimeField(verbose_name='Задача закрыта')),
                ('control_date', models.DateTimeField(verbose_name='Контрольный срок')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
