# Generated by Django 4.2.1 on 2023-06-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='close_date',
            field=models.DateTimeField(blank=True, verbose_name='Задача закрыта'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='control_date',
            field=models.DateTimeField(blank=True, verbose_name='Контрольный срок'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='open_date',
            field=models.DateTimeField(blank=True, verbose_name='Задача открыта'),
        ),
    ]
